### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by CodeCreator** [duetosymmetry/arXiv-keys#11]
Hi & thank you for this great little extension!

I noticed that a few weeks ago, the extension has stopped working.

On Google Chrome, I see the following exception:
```
abs.js:50 Uncaught ReferenceError: arXivKeys is not defined
    at abs.js:50:1
    at abs.js:54:2
```

**Comment by duetosymmetry** [comment]
Thanks for reporting the issue, Alexander! Nothing in the extension itself changed. If you remove the extension from Chrome and then add it again, does the issue persist? (I've encountered a random extension corruption event in the past). If that doesn't work then we'll have to try to debug for real...

**Comment by CodeCreator** [comment]
Thanks! That did the trick :) Sorry for raising a false alarm!

**Comment by duetosymmetry** [comment]
Thanks for reporting back!
